export default 
[
    {Description: "A",
    Image: "/assets/alphabet_image/A.jpg" },
    {Description: "B",
    Image: "/assets/alphabet_image/B.jpg" },
    {Description: "C",
    Image: "/assets/alphabet_image/C.jpg" },
    {Description: "D",
    Image: "/assets/alphabet_image/D.jpg" },
    {Description: "E",
    Image: "/assets/alphabet_image/E.jpg" },
    {Description: "F",
    Image: "/assets/alphabet_image/F.jpg" },
    {Description: "G",
    Image: "/assets/alphabet_image/G.jpg" },
    {Description: "H",
    Image: "/assets/alphabet_image/H.jpg" },
    {Description: "I",
    Image: "/assets/alphabet_image/I.jpg" },
    {Description: "J",
    Image: "/assets/alphabet_image/J.jpg" },
    {Description: "K",
    Image: "/assets/alphabet_image/K.jpg" },
    {Description: "L",
    Image: "/assets/alphabet_image/L.jpg" },
    {Description: "M",
    Image: "/assets/alphabet_image/M.jpg" },
    {Description: "N",
    Image: "/assets/alphabet_image/N.jpg" },
    {Description: "O",
    Image: "/assets/alphabet_image/O.jpg" },
    {Description: "P",
    Image: "/assets/alphabet_image/P.jpg" },
    {Description: "Q",
    Image: "/assets/alphabet_image/Q.jpg" },
    {Description: "R",
    Image: "/assets/alphabet_image/R.jpg" },
    {Description: "S",
    Image: "/assets/alphabet_image/S.jpg" },
    {Description: "T",
    Image: "/assets/alphabet_image/T.jpg" },
    {Description: "U",
    Image: "/assets/alphabet_image/U.jpg" },
    {Description: "V",
    Image: "/assets/alphabet_image/V.jpg" },
    {Description: "W",
    Image: "/assets/alphabet_image/W.jpg" },
    {Description: "X",
    Image: "/assets/alphabet_image/X.jpg" },
    {Description: "Y",
    Image: "/assets/alphabet_image/Y.jpg" },
    {Description: "Z",
    Image: "/assets/alphabet_image/Z.jpg" },
    {Description: "1",
    Image: "/assets/alphabet_image/1.jpg" },
    {Description: "2",
    Image: "/assets/alphabet_image/2.jpg" },
    {Description: "3",
    Image: "/assets/alphabet_image/3.jpg" },
    {Description: "4",
    Image: "/assets/alphabet_image/4.jpg" },
    {Description: "5",
    Image: "/assets/alphabet_image/5.jpg" },
    {Description: "6",
    Image: "/assets/alphabet_image/6.jpg" },
    {Description: "7",
    Image: "/assets/alphabet_image/7.jpg" },
    {Description: "8",
    Image: "/assets/alphabet_image/8.jpg" },
    {Description: "9",
    Image: "/assets/alphabet_image/9.jpg" },
    {Description: "10",
    Image: "/assets/alphabet_image/10.jpg" }
    
]